tool/script support & hotstart custom chaindir
- hotstart start now takes --chaindir <dir> to start from a custom nodeos data directory
- DoHTestLib init() and fixtureInit() now take a string argument that is passed to hotstart start
  (so tests can use the new --chaindir option to select which nodeos data directory to use)
- added tool/script execution suppor to cth via --exec,-e (use --dump to see the output on success)
- changed coldstart/stop to try to shutdown nodeos more gracefully via kill -INT first
- jailbroken cth so that it can be invoked from any directory (e.g. you can now just add your
  cth installation directory eg. ~/cth/ to your PATH)
- fixed CthTestDriver.js printing/returning JS buffer object instead of buffer.toString()
- fixed hotstart start (via CthTest.js::init()) not logging errors
- removed cth refuses to run when cth already running (bad idea, prevents cth calling cth -e)
- fixed cth failing if/when the default 'tests' subdirectory doesn't exist

diff --git a/drivers/coldstart/stop b/drivers/coldstart/stop
--- a/drivers/coldstart/stop
+++ b/drivers/coldstart/stop
@@ -1,23 +1,55 @@
 #!/bin/bash
 
-# make sure the current working dir is the driver's working dir
+# Make sure the current working directory is the driver's working directory
 # at ../../local/coldstart/
 cd "$(dirname "$0")"
 if ! cd "../../local/coldstart"; then
-  echo "coldstart stop: cannot change directory to local/coldstart; assuming no coldstart nodeos to stop"
-  exit 0
+    echo "coldstart stop: cannot change directory to local/coldstart; assuming no coldstart nodeos to stop"
+    exit 0
 fi
 
 if [ -f "./nodeos.pid" ]; then
-pid=`cat "./nodeos.pid"`
-echo $pid
-kill $pid
-rm -r "./nodeos.pid"
-echo -ne "Stoping nodeos.."
-while true; do
-[ ! -d "/proc/$pid/fd" ] && break
-echo -ne "."
-sleep 1
-done
-echo -ne "\nnodeos stopped.\n"
+    pid=$(cat "./nodeos.pid")
+    echo $pid
+
+    # Send the INT signal to the process
+    kill -INT $pid
+    echo -ne "Stopping nodeos..."
+
+    # Wait up to 5 seconds for the process to respond to TERM signal
+    timeout=5
+    while [ $timeout -gt 0 ]; do
+        if [ ! -d "/proc/$pid/fd" ]; then
+            echo -ne "\nnodeos stopped (-INT).\n"
+            # Remove the pid file
+            rm -r "./nodeos.pid"
+            # done
+            exit 0
+        fi
+        echo -ne "."
+        sleep 1
+        ((timeout--))
+    done
+
+    # If the process did not respond to TERM, forcefully terminate with KILL signal
+    echo -ne "\nNodeos did not respond to TERM signal. Forcefully terminating with KILL signal..."
+    kill -KILL $pid
+
+    # Wait for the process to respond to KILL signal
+    timeout=5
+    while [ $timeout -gt 0 ]; do
+        if [ ! -d "/proc/$pid/fd" ]; then
+            echo -ne "\nnodeos stopped (-KILL).\n"
+            # Remove the pid file
+            rm -r "./nodeos.pid"
+            # done
+            exit
+        fi
+        echo -ne "."
+        sleep 1
+        ((timeout--))
+    done
+
+    echo -ne "\nERROR: could not stop nodeos even with kill -KILL.\n"
+    exit 1
 fi
